manifest:
    self:
        path: l2cap_reproducer

    version: "1.2"

    remotes:
        -   name: nordic
            url-base: https://github.com/nrfconnect

        -   name: robitzki
            url-base: https://github.com/TorstenRobitzki

    projects:
        -   name: sdk-nrf
            description: Nordic SDK
            remote: nordic
            path: nrf
            revision: v2.8.0
            import: true

        -   name: zephyr
            remote: robitzki
            repo-path: sdk-zephyr
            revision: 6f7193b063f4719e7e2cd2e3d690bdcb8d12044b
            import:
                # In addition to the zephyr repository itself, NCS also
                # imports the contents of zephyr/west.yml at the above
                # revision. Only the projects explicitly named in the
                # following allowlist are imported.
                #
                # Note that the zephyr west extensions (like 'build', 'flash',
                # 'debug', etc.) are automatically provided by this import, so
                # there's no need to add a redundant west-commands: key for
                # the zephyr project.
                #
                # Please keep this list sorted alphabetically.
                name-allowlist:
                  - TraceRecorderSource
                  - canopennode
                  - chre
                  - cmsis
                  - cmsis-dsp
                  - cmsis-nn
                  - edtt
                  - fatfs
                  - hal_nordic
                  - hal_st # required for ST sensors (unrelated to STM32 MCUs)
                  - hal_wurthelektronik
                  - hostap
                  - liblc3
                  - libmetal
                  - littlefs
                  - loramac-node
                  - lvgl
                  - lz4
                  - mipi-sys-t
                  - nanopb
                  - net-tools
                  - nrf_hw_models
                  - open-amp
                  - picolibc
                  - segger
                  - tinycrypt
                  - tf-m-tests
                  - uoscore-uedhoc
                  - zcbor
                  - zscilib