manifest:
    self:
        path: l2cap_reproducer

    version: "1.2"

    remotes:
        -   name: nordic
            url-base: https://github.com/nrfconnect

    projects:
        -   name: sdk-nrf
            description: Nordic SDK
            remote: nordic
            path: nrf
            revision: v2.8.0
            import: true
